# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-LogNotify
version:      0.1
version_from: lib/Apache2/LogNotify.pm
installdirs:  perl
requires:
    Apache2::Connection:           2.000003
    Apache2::Const:                2.000003
    Apache2::Log:                  2.000003
    Apache2::Process:              2.000003
    Apache2::RequestRec:           2.000003
    Apache2::RequestUtil:          2.000003
    Apache2::ServerRec:            2.000003
    Apache2::ServerUtil:           2.000003
    APR::Finfo:                    0.009000
    APR::Table:                    0.009000
    IPC::Cache:                    0.02
    Mail::Mailer:                  1.74

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
